# Site settings
title: TMD
email: irvin_e@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  Irvin's data science journey
baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
twitter_username: twitter_username
github_username:  irvintmd

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  writings:
    output: true
    permalink: /writings/:path/


